### PR TITLE
Indonesian

### PR DESCRIPTION
**Pull request by RhezaBoge**
I've made an Indonesian stemmer file. I hope it works well. Please try it and give some input if something is wrong.

### CODE REVIEW

**Comment by smit1678** [comment]
Thanks @RhezaBoge! Great to see this. I mentioned this to @russbiggs and he'll help take a look at getting this integrated into the PDC documentation site to test. Tagging him here for a review.

**Comment by smit1678** [comment]
@russbiggs I tested this locally and it is working well with basic search terms: 

HOT-PDC Training Site 2019-07-15 16-36-48

I think this is good to merge. Tagging you with a review.

**Comment by russbiggs** [comment]
@smit1678  Do we have plans to work off this fork indefinitely or is the goal to get this merged into the main repo?

**Comment by smit1678** [comment]
> Do we have plans to work off this fork indefinitely or is the goal to get this merged into the main repo?

I think our primary goal should be to have it in the main repo but I think we can put this into action before it's fully merged into the main.

I think there are also a few more things that I think we need to get done before we can do a PR based on the contribution guidelines: 
- [ ] Create unit tests for Indonesia language support. Must cover at least 4 test cases (wildcard and stemming)
- [ ] Test and ensure that unit tests can be run on all Lunr versions
- [ ] Add new language to README.md
- [ ] Re-build the files following the repository guidelines

@RhezaBoge do you think you can add in the unit tests before we call this PR finished? Any other items you want to add here based off our our test yesterday?

**Comment by russbiggs** [comment]
One thing sticks out to me which is the the lack of using the ``` lunr.stemmerSupport.Among ``` function for capturing patterns. Seems like all the other stemmers in the package follow this pattern.  Currently this stemmer is 10x bigger than the others at 325kb due to this difference. 

Keep in mind I know nothing about Indonesian linguistics so I'm definitely interested if the ``` Among ``` function isn't suitable for Indonesian stemming, just guessing the pattern difference (and file size) might give some issue in getting it contributed back into the main repo.

**Comment by russbiggs** [comment]
@RhezaBoge can you respond about my comment above?  I'll be in Jakarta in a few weeks as well so I would be happy to try to meet up and discuss a bit as well.

**Comment by RhezaBoge** [comment]
Hi @russbiggs I'm sorry for the late response. yes, I've tried to think of the "Among" function and how we can implement that function in Bahasa (Indonesian linguistics). It's quite difficult to use the "Among" function in Bahasa. Many studies have tried to build an Indonesian stemmer but it is difficult, that's why we still have difficulty finding a good Indonesian stemmer in this country :). I do not know how I can explain about it, there are many differences like Indonesian does not have tenses, plural and singular nouns, etc.

**Pull request merged**
